apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testitems.operator.io
spec:
  group: operator.io
  names:
    kind: TestItem
    listKind: TestItemList
    plural: testitems
    singular: testitem
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            type: object
          spec:
            nullable: false
            properties:
              scope:
                enum:
                - Namespaced
                - Cluster
                type: string
              string:
                nullable: false
                type: string
            required:
            - scope
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.operator.io
spec:
  group: operator.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              result:
                nullable: false
                type: string
            required:
            - result
            type: object
          spec:
            nullable: false
            properties:
              name:
                nullable: false
                type: string
              organization:
                nullable: false
                type: string
              project:
                nullable: false
                type: string
            required:
            - name
            - organization
            - project
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - operator.io
  resources:
  - testitems
  - projects
  verbs:
  - '*'
- apiGroups:
  - operator.io
  resources:
  - testitems/status
  - projects/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-operator-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: simple-operator
  name: simple-operator-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator-deployment: simple-operator
  template:
    metadata:
      labels:
        operator-deployment: simple-operator
    spec:
      containers:
      - env:
        - name: test
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/operator/operator:latest
        name: simple-operator
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 2024
          runAsNonRoot: true
          runAsUser: 2024
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
---

