apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testitems.sonarcloud.io
spec:
  group: sonarcloud.io
  names:
    kind: TestItem
    listKind: TestItemList
    plural: testitems
    singular: testitem
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            type: object
          spec:
            nullable: false
            properties:
              scope:
                enum:
                - Namespaced
                - Cluster
                type: string
              string:
                nullable: false
                type: string
            required:
            - scope
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.sonarcloud.io
spec:
  group: sonarcloud.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              result:
                nullable: false
                type: string
            required:
            - result
            type: object
          spec:
            nullable: false
            properties:
              name:
                nullable: false
                type: string
              organization:
                nullable: false
                type: string
              project:
                nullable: false
                type: string
            required:
            - name
            - organization
            - project
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - sonarcloud.io
  resources:
  - testitems
  - projects
  verbs:
  - '*'
- apiGroups:
  - sonarcloud.io
  resources:
  - testitems/status
  - projects/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
---
